package ventanas;
import Code.Usuario;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author Troxblack
 */
public class FormRegistrarse extends javax.swing.JDialog {

    int xMouse , yMouse;
    public FormRegistrarse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonRegistrarse = new javax.swing.JButton();
        jLabelDraw = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseExited(evt);
            }
        });
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 100, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 120, 30));

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 120, 30));
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Usuario :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirmar Contraseña :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegistrarseMouseExited(evt);
            }
        });
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 120, -1));

        jLabelDraw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelDrawMouseDragged(evt);
            }
        });
        jLabelDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelDrawMousePressed(evt);
            }
        });
        getContentPane().add(jLabelDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 410));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fc813e57424d1ad9576f9066812f670f.jpeg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 319, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseEntered
        jButtonCancelar.setBackground(new java.awt.Color(218,48,52));
    }//GEN-LAST:event_jButtonCancelarMouseEntered

    private void jButtonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseExited
        jButtonCancelar.setBackground(new java.awt.Color(209,224,238));
    }//GEN-LAST:event_jButtonCancelarMouseExited

    private void jButtonRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarseMouseEntered
        jButtonRegistrarse.setBackground(new java.awt.Color(64,217,26));
    }//GEN-LAST:event_jButtonRegistrarseMouseEntered

    private void jButtonRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarseMouseExited
        jButtonRegistrarse.setBackground(new java.awt.Color(209,224,238));
    }//GEN-LAST:event_jButtonRegistrarseMouseExited

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        String nombre = jTextFieldUsuario.getText();
        String contraseña = jPasswordField1.getText();
        String confirmarContraseña = jPasswordField2.getText();
        if( !nombre.matches("[a-zA-Z0-9].*")){
            JOptionPane.showMessageDialog(null,"Porfavor Ingrese nombre de usuario valido" );
            jPasswordField1.setText(null);
            jPasswordField2.setText(null);
            jTextFieldUsuario.setText(null);
        }
        else if(cargarUsuario()!=null){
                if(cargarUsuario().getNombre().equals(nombre)){
                    JOptionPane.showMessageDialog(null,"El nombre de usuario ya esta en uso");
                    jTextFieldUsuario.setText(null);
                    jPasswordField1.setText(null);
                    jPasswordField2.setText(null);
                }
        }
        else if((contraseña.equals(""))||(confirmarContraseña.equals(""))){
            JOptionPane.showMessageDialog(null,"Porfavor introduzca contraseña valida" );
            jPasswordField1.setAction(null);
            jPasswordField2.setAction(null);
        }
        else if( (!contraseña.equals(confirmarContraseña))){
            JOptionPane.showMessageDialog(null,"Las contraseñas no coinciden" );
            jPasswordField1.setAction(null);
            jPasswordField2.setAction(null);
        }
        else{
                String usuario = nombre + ";" + contraseña + ";";
                guardarUsuario(usuario,"datosPersona.txt");

                JOptionPane.showMessageDialog(null,"Cuenta registrada con exito!" );
                this.dispose();    
        }
    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    private void jLabelDrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDrawMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabelDrawMousePressed

    private void jLabelDrawMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDrawMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse ,y - yMouse);
    }//GEN-LAST:event_jLabelDrawMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormRegistrarse dialog = new FormRegistrarse(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public static void guardarUsuario(String datos, String ruta){
    File archivo = new File(ruta); //load archivo
    try{
      try{
        archivo.delete();
      }catch(Exception e){
        System.out.println(e);
      }
      FileWriter escribir = new FileWriter(archivo,true); //Escribir en archivo en linea
      PrintWriter escritor = new PrintWriter(escribir); //Escribir en archivo
      
      escritor.print(datos); //escribir
      
      escritor.close();//cerrar escritor
      escribir.close();
    } catch(IOException e) {
      System.out.println(e);
    }
  }
  
  public static Usuario cargarUsuario() {
    try {
      BufferedReader archivo = new BufferedReader(new FileReader("datosPersona.txt"));
      if(archivo.readLine() != null){
      String linea; // leer primer linea
      while ((linea = archivo.readLine()) != null) { // Avanzar siempre que existan lineas   
      }
      String[] campos = linea.split(";");
      Usuario persona = new Usuario(campos[0],campos[1]);
      archivo.close();
      return persona;
      }
      return null;
    } catch (FileNotFoundException ex) {
      Logger.getLogger(FormRegistrarse.class.getName()).log(Level.SEVERE, null, ex);
      return null;
    } catch (IOException e) {
      System.out.println(e);
      return null;
    }
  }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDraw;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
