package ventanas;
import Code.*;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author Troxblack
 */
public class Login extends javax.swing.JFrame {

    int xMouse , yMouse;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabeltxt1 = new javax.swing.JLabel();
        jLabeltxt2 = new javax.swing.JLabel();
        jButtonRegistrarse = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jLabelDraw = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jPablo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setText("Salir");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseExited(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 120, -1));

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 120, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 120, -1));

        jLabeltxt1.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltxt1.setText("Usuario :");
        getContentPane().add(jLabeltxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 60, 20));

        jLabeltxt2.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltxt2.setText("Contraseña :");
        getContentPane().add(jLabeltxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 120, -1));

        jButtonLogin.setText("Entrar");
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseExited(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 120, -1));

        jLabelDraw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelDrawMouseDragged(evt);
            }
        });
        jLabelDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelDrawMousePressed(evt);
            }
        });
        getContentPane().add(jLabelDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 410));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fc813e57424d1ad9576f9066812f670f.jpeg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 410));

        jPablo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IMG_0070.jpg"))); // NOI18N
        getContentPane().add(jPablo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed

    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jLabelDrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDrawMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabelDrawMousePressed

    private void jLabelDrawMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDrawMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse ,y - yMouse);
    }//GEN-LAST:event_jLabelDrawMouseDragged

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        jButtonSalir.setBackground(new java.awt.Color(218,48,52));
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseExited
        jButtonSalir.setBackground(new java.awt.Color(209,224,238));
    }//GEN-LAST:event_jButtonSalirMouseExited

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        new FormRegistrarse(this,true).setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String contraseñaL = jPasswordField1.getText();
        String nombreL = jTextFieldUsuario.getText();
        Usuario usuario = null;
        if(cargarUsuario()!=null){
            usuario = new Usuario(cargarUsuario().getNombre(),cargarUsuario().getContraseña());
            if ((nombreL.equals(usuario.getNombre())) && (contraseñaL.equals(usuario.getContraseña()))){
           JOptionPane.showMessageDialog(null,"Sesion iniciada con exito!" );
           new Menu(this,true).setVisible(true);
           this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Usuario o Contraseña erronea" );
            jPasswordField1.setText("");
            jTextFieldUsuario.setText("");
        }
        }
        else{
            JOptionPane.showMessageDialog(null,"Usuario o Contraseña erronea" );
            jPasswordField1.setText("");
            jTextFieldUsuario.setText(""); 
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseEntered
        jButtonLogin.setBackground(new java.awt.Color(64,217,26));
    }//GEN-LAST:event_jButtonLoginMouseEntered

    private void jButtonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseExited
        jButtonLogin.setBackground(new java.awt.Color(209,224,238));
    }//GEN-LAST:event_jButtonLoginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    public static Usuario cargarUsuario() {
    try {
      BufferedReader archivo = new BufferedReader(new FileReader("datosPersona.txt"));

      String linea; // leer primer linea
      while ((linea = archivo.readLine()) != null) { // Avanzar siempre que existan lineas
        String[] campos = linea.split(";"); // separar en campos por ";"
        Usuario persona = new Usuario((campos[0]),(campos[1]));//Añadir camos a futuro!
        return persona;
      }
    } catch (FileNotFoundException ex) {
      Logger.getLogger(FormRegistrarse.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException e) {
      System.out.println(e);
    }
    return null;
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelDraw;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabeltxt1;
    private javax.swing.JLabel jLabeltxt2;
    private javax.swing.JLabel jPablo;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
